Creates CS Tooling
RockefellerArchiveCenter/ursa_major pull request #152
Opened 2021-12-17 20:55 UTC by HaSistrunk

Sets up application for continuous deployment:

- adds appspec file
- update application configs
- add deploy keys to Travis configs
- improve port settings

2021-12-17 21:03 UTC, p-galligan approved these changes
Looks good to me.

2021-12-17 22:32 UTC, helrond commented on appspec.yml.deploy
> +    - location: deploy_scripts/set_permissions.sh
This should be in the AfterInstall step.

2021-12-17 22:33 UTC, helrond requested changes
Just one minor thing....

2021-12-20 18:48 UTC, helrond approved these changes

2021-12-20 20:32 UTC, bonniegee approved these changes

2021-12-20 21:11 UTC, bonniegee commented on ursa_major/config.py.deploy
> +DERIVATIVE_CREATION_DIR = "{DERIVATIVE_CREATION_DIR}"
@HaSistrunk I think there's a missing `$` here.

2021-12-20 21:16 UTC, HaSistrunk commented
I'm also missing a SCHEMA_PATH variable that was in the original config. Trying to figure out how that's used, but assuming it's necessary.

2021-12-20 21:25 UTC, bonniegee commented
> I'm also missing a SCHEMA_PATH variable that was in the original config. Trying to figure out how that's used, but assuming it's necessary.

I'm having trouble finding the commit that did this, but I believe this config was removed when we added `rac-schemas` and it just never made its way to deployment.

2021-12-21 16:03 UTC, merged